; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
 
monitor_speed = 115200 
upload_speed = 921600 

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1

lib_extra_dirs = lib
lib_deps =
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  tzapu/WiFiManager
  esphome/AsyncTCP-esphome
  esphome/ESPAsyncWebServer-esphome
  adafruit/Adafruit NeoPixel

[env:example_relay_pulse]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_example_relay_pulse.cpp>

[env:4relays]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_4relays.cpp>

[env:4relaysWithSensor]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_4relays_withsensor.cpp>
lib_deps =
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  tzapu/WiFiManager
  esphome/AsyncTCP-esphome
  esphome/ESPAsyncWebServer-esphome
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit AHTX0
  adafruit/Adafruit BMP280 Library
  adafruit/Adafruit Unified Sensor

[env:garage_door]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_garage_door.cpp>
lib_deps =
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  tzapu/WiFiManager
  esphome/AsyncTCP-esphome
  esphome/ESPAsyncWebServer-esphome
  adafruit/Adafruit NeoPixel
  pololu/VL53L0X

[env:example_veml7700]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_example_veml7700.cpp>
lib_deps =
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  tzapu/WiFiManager
  esphome/AsyncTCP-esphome
  esphome/ESPAsyncWebServer-esphome
  adafruit/Adafruit NeoPixel
  adafruit/Adafruit VEML7700 Library

[env:example_vl53l0x]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_example_vl53l0x.cpp>
lib_deps =
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  tzapu/WiFiManager
  esphome/AsyncTCP-esphome
  esphome/ESPAsyncWebServer-esphome
  adafruit/Adafruit NeoPixel
  pololu/VL53L0X

[env:micronova]
board_build.flash_mode = dio 
board_build.mcu = esp32c3 
board_build.f_cpu = 160000000L

build_src_filter = +<esp32/main_micronova.cpp>

[env:esp02s]
platform = espressif8266
board = esp_wroom_02
framework = arduino
 
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

build_src_filter = +<esp02s/main_example_server.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
  
[env:light_switch]
platform = espressif8266
board = esp_wroom_02
framework = arduino
 
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_light_switch.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
  knolleary/PubSubClient

[env:light_switch_esp02s_ota]
platform = espressif8266
board = esp_wroom_02
framework = arduino
  
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

upload_protocol = espota

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_light_switch.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
  knolleary/PubSubClient

[env:shutter_esp02s]
platform = espressif8266
board = esp_wroom_02
framework = arduino
 
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_shutter.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
  knolleary/PubSubClient

[env:shutter_esp02s_ota]
platform = espressif8266
board = esp_wroom_02
framework = arduino
  
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

upload_protocol = espota

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_shutter.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
  knolleary/PubSubClient

[env:starter_esp02s]
platform = espressif8266
board = esp_wroom_02
framework = arduino
 
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_starter.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0

[env:starter_esp02s_ota]
platform = espressif8266
board = esp_wroom_02
framework = arduino
 
monitor_speed  = 115200
upload_speed   = 115200
board_build.flash_size = 4MB
board_build.flash_mode = dout

upload_protocol = espota

build_flags =
    -DWEBSOCKET_DISABLED

build_src_filter = +<esp02s/main_starter.cpp>

lib_deps =
  tzapu/WiFiManager
  bblanchon/ArduinoJson @ ^6.21.0
